[package]
name = "habi-cli"
description = "Command-line interface for Habi."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "habi"
path = "src/main.rs"

[dependencies]
habi-core.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ctrlc.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
