/**
 * Development-only design preview.
 *
 * When the UI runs in a plain browser (`pnpm dev`, no Tauri), IPC calls are
 * answered from JSON fixtures generated by the real Rust core
 * (`cargo test -p habi-core --test ui_fixtures -- --ignored`). This exists so
 * screens can be inspected with realistic data during design work. It is
 * loaded only in Vite dev mode outside Tauri and is never part of a build;
 * the tab title says it is fixture data.
 */
import { mockIPC } from "@tauri-apps/api/mocks";
import details from "../test/fixtures/item-details.json";
import library from "../test/fixtures/library.json";
import billing from "../test/fixtures/overview-billing-service.json";
import monorepo from "../test/fixtures/overview-platform-monorepo.json";
import plan from "../test/fixtures/plan-install.json";

type Args = Record<string, unknown> | undefined;

const overviews: Record<string, unknown> = {
  [billing.project.id]: billing,
  [monorepo.project.id]: monorepo,
};

const projects = [billing.project, monorepo.project];
const source = billing.sources[0];
let settings = { autoRefreshHours: 12, defaultClients: ["claude-code"] };

function answer(cmd: string, args: Args): unknown {
  const a = args ?? {};
  switch (cmd) {
    case "app_info":
      return {
        version: "0.1.0-preview",
        dataDir: "~/Library/Application Support/com.acltabontabon.Habi",
        platform: "macos",
        gitAvailable: true,
        ghAvailable: true,
        glabAvailable: false,
        startupError: null,
      };
    case "get_settings":
      return settings;
    case "set_settings":
      settings = a.settings as typeof settings;
      return settings;
    case "recent_projects":
      return projects;
    case "open_recent_project":
      return projects.find((p) => p.id === a.projectId);
    case "project_overview":
      return overviews[a.projectId as string];
    case "list_sources":
      return [source];
    case "library":
      return library;
    case "item_detail":
      return (details as Record<string, unknown>)[a.itemId as string];
    case "item_file":
      return {
        path: a.path,
        text: "(file content is not part of the preview fixtures)",
        size: 0,
        binary: false,
      };
    case "history":
    case "list_contributions":
    case "check_runs":
    case "list_skills":
    case "suggest_conditions":
      return [];
    case "discover_project":
      return { skills: [], instructions: [], limits: [], inspectedAt: new Date().toISOString() };
    case "plan_install":
      return plan;
    case "read_project_excerpt":
      return {
        path: a.path,
        startLine: Math.max(1, ((a.line as number | null) ?? 1) - 3),
        lines: ["(excerpt not available in the design preview)"],
        highlight: a.line ?? null,
        totalLines: 1,
      };
    case "watch_project":
    case "unwatch_project":
    case "cancel_job":
    case "log_ui_error":
      return null;
    case "plugin:event|listen":
      return 1;
    case "plugin:event|unlisten":
      return null;
    default:
      throw { code: "unsupported", message: `“${cmd}” is not available in the design preview.` };
  }
}

export function installPreview() {
  mockIPC((cmd, args) => answer(cmd, args as Args));
  // The mode is named in the tab title, not on screen.
  document.title = "Habi — design preview (fixture data)";
}
