/**
 * Development-only design preview.
 *
 * When the UI runs in a plain browser (`pnpm dev`, no Tauri), IPC calls are
 * answered from JSON fixtures generated by the real Rust core
 * (`cargo test -p habi-core --test ui_fixtures -- --ignored`). This exists so
 * screens can be inspected with realistic data during design work. It is
 * loaded only in Vite dev mode outside Tauri and is never part of a build;
 * the tab title says it is fixture data.
 */
import { mockIPC } from "@tauri-apps/api/mocks";
import catalog from "../test/fixtures/catalog.json";
import details from "../test/fixtures/item-details.json";
import library from "../test/fixtures/library.json";
import billing from "../test/fixtures/overview-billing-service.json";
import monorepo from "../test/fixtures/overview-platform-monorepo.json";
import plan from "../test/fixtures/plan-install.json";

type Args = Record<string, unknown> | undefined;

/** Cancels the fetch the design preview is holding open, if any. */
let heldFetch: (() => void) | null = null;

const overviews: Record<string, unknown> = {
  [billing.project.id]: billing,
  [monorepo.project.id]: monorepo,
};

const projects = [billing.project, monorepo.project];
const source = billing.sources[0];
let settings = { autoRefreshHours: 12, defaultClients: ["claude-code"] };

// A newer release waiting, then what updating to it changed: so the offer, the
// report and the marks in the index can all be looked at.
const commit = (n: number) => String(n).repeat(40).slice(0, 40);
const v = (label: string, n: number) => ({ label, release: true, commit: commit(n) });
let update: "waiting" | "updated" | "seen" = "waiting";
const checkedAt = () => new Date().toISOString();
const updateCheck = () => ({
  sourceId: source?.id ?? "",
  current: update === "waiting" ? v("v6.4.1", 1) : v("v6.4.2", 2),
  latest: v("v6.4.2", 2),
  available: update === "waiting",
  checkedAt: checkedAt(),
});
const report = () => ({
  sourceId: source?.id ?? "",
  from: v("v6.4.1", 1),
  to: v("v6.4.2", 2),
  at: checkedAt(),
  added: [{ id: "incident-notes", title: "Incident notes" }],
  updated: [
    { id: "api-contract-review", title: "API contract review" },
    { id: "github-pr-summary", title: "GitHub PR summary" },
  ],
  removed: [{ id: "old-release-checklist", title: "Old release checklist" }],
});

function answer(cmd: string, args: Args): unknown {
  const a = args ?? {};
  switch (cmd) {
    case "app_info":
      return {
        version: "0.1.0-preview",
        dataDir: "~/Library/Application Support/com.acltabontabon.Habi",
        platform: "macos",
        gitAvailable: true,
        ghAvailable: true,
        glabAvailable: false,
        startupError: null,
      };
    case "get_settings":
      return settings;
    case "set_settings":
      settings = a.settings as typeof settings;
      return settings;
    case "recent_projects":
      return projects;
    case "open_recent_project":
      return projects.find((p) => p.id === a.projectId);
    case "project_overview":
      return overviews[a.projectId as string];
    case "list_sources":
      return [source];
    case "source_updates":
      return update === "seen" ? [] : [updateCheck()];
    case "check_source_update":
      return updateCheck();
    case "refresh_source":
      update = "updated";
      return { changed: true, source };
    case "source_update_report":
      return update === "updated" ? report() : null;
    case "dismiss_update_report":
      update = "seen";
      return null;
    // A folder to choose and look inside, so the connect page can be seen with something in it.
    case "pick_library_folder":
      return "/Users/aclt/Workspace/ai-standard-packs";
    case "inspect_import":
      return {
        origin: "ai-standard-packs",
        candidates: library.items.map((i) => ({
          path: i.path,
          name: i.name,
          title: i.title,
          description: i.description,
          license: null,
          hasMetadata: false,
          files: i.files.map((f) => f.path),
          size: 0,
          problems: [],
          complete: true,
          digest: i.contentDigest,
          duplicate: null,
          suggestedName: null,
        })),
        notes: [],
      };
    case "catalog":
      return catalog;
    case "catalog_fits":
      return [];
    // Sample figures, only so the page can be looked at; the real ones come from GitHub.
    case "catalog_repo_facts":
      return {
        stars: 4200,
        forks: 310,
        pushedAt: new Date(Date.now() - 3 * 86_400_000).toISOString(),
        createdYear: 2025,
        archived: false,
        fetchedAt: new Date().toISOString(),
      };
    // A connection that never finishes, so the waiting screen can be looked at;
    // cancelling it fails it the way the core does.
    case "connect_catalog_entry":
      return new Promise((_, reject) => {
        heldFetch = () => reject({ code: "cancelled", message: "cancelled" });
      });
    case "library":
      return library;
    case "item_detail":
      return (details as Record<string, unknown>)[a.itemId as string];
    case "item_file":
      return {
        path: a.path,
        text: "(file content is not part of the preview fixtures)",
        size: 0,
        binary: false,
      };
    case "history":
    case "list_contributions":
    case "check_runs":
    case "list_skills":
    case "suggest_conditions":
      return [];
    case "discover_project":
      return { skills: [], instructions: [], limits: [], inspectedAt: new Date().toISOString() };
    case "plan_install":
      return plan;
    // Skills in the person's own folders: the same plan, rooted at the home folder.
    case "plan_install_machine":
      return {
        ...plan,
        title: "Install for Claude Code on this machine",
        project: "~",
        items: plan.items.slice(0, 1),
        changes: [
          ...plan.changes.filter((c) => c.kind === "skillFile" && c.clients.includes("claude-code")),
          ...plan.changes.filter((c) => c.kind === "lockFile"),
        ],
      };
    case "machine_install_preview":
      return [];
    case "read_project_excerpt":
      return {
        path: a.path,
        startLine: Math.max(1, ((a.line as number | null) ?? 1) - 3),
        lines: ["(excerpt not available in the design preview)"],
        highlight: a.line ?? null,
        totalLines: 1,
      };
    case "cancel_job":
      heldFetch?.();
      heldFetch = null;
      return true;
    case "watch_project":
    case "unwatch_project":
    case "log_ui_error":
      return null;
    case "plugin:event|listen":
      return 1;
    case "plugin:event|unlisten":
      return null;
    default:
      throw { code: "unsupported", message: `“${cmd}” is not available in the design preview.` };
  }
}

export function installPreview() {
  mockIPC((cmd, args) => answer(cmd, args as Args));
  // The mode is named in the tab title, not on screen.
  document.title = "Habi — design preview (fixture data)";
}
