// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Applicability } from "./Applicability";
import type { ModuleMatch } from "./ModuleMatch";
import type { Scope } from "./Scope";

export type ApplicabilityResult = { applicability: Applicability, scope: Scope, 
/**
 * Per-module results, most relevant first.
 */
modules: Array<ModuleMatch>, reason: string, specificity: number, };
