// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What went wrong the last time the author prepared or sent this
 * contribution. Cleared by the next success.
 */
export type AttentionKind = "prepare" | "send" | "remoteMoved";
