// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionKind } from "./AttentionKind";

export type Attention = { kind: AttentionKind, message: string, at: string, };
