// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingKind } from "./BindingKind";

export type BindingChoice = { name: string, kind: BindingKind, description: string | null, candidates: Array<string>, selected: string | null, };
