// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingKind } from "./BindingKind";

export type BindingSpec = { name: string, kind: BindingKind, glob: string | null, description: string | null, };
