// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublisherKind } from "./PublisherKind";

/**
 * Who is behind the repository, and what supports saying so. Ownership is
 * one fact; whether anyone at Habi has inspected the content is another.
 */
export type CatalogPublisher = { name: string, kind: PublisherKind, 
/**
 * The account that owns the repository.
 */
owner: string, };
