// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnershipMethod } from "./OwnershipMethod";

export type CatalogOwnership = { method: OwnershipMethod, 
/**
 * The day this was last checked.
 */
checked: string, 
/**
 * What was checked, in a sentence.
 */
evidence: string, };
