// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";

/**
 * What was fetched of a library.
 */
export type CatalogFetched = { snapshot: string, snapshotAt: string | null, 
/**
 * The branch the repository's `HEAD` named at the last check.
 */
branch: string | null, 
/**
 * The release tag this was read at (`v6.4.2`), if it was read at one.
 */
release: string | null, 
/**
 * The newest commit: its subject, author and date.
 */
commitSummary: string | null, 
/**
 * The date of the newest commit (`YYYY-MM-DD`).
 */
updated: string | null, freshness: Freshness, warning: string | null, };
