// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogReview = { revision: string, date: string, by: string, scope: string, 
/**
 * The fetched library is still at the reviewed revision.
 */
current: boolean, };
