// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerKind } from "./TriggerKind";

/**
 * One feature of a project that makes the catalog suggest this library's
 * skills: a dependency, a file or a detected tag, as the registry's hints say.
 */
export type CatalogTrigger = { kind: TriggerKind, text: string, };
