// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogAvailability } from "./CatalogAvailability";
import type { CatalogFetched } from "./CatalogFetched";
import type { CatalogOwnership } from "./CatalogOwnership";
import type { CatalogPublisher } from "./CatalogPublisher";
import type { CatalogReview } from "./CatalogReview";
import type { CatalogStatus } from "./CatalogStatus";
import type { CatalogTrigger } from "./CatalogTrigger";
import type { ErrorInfo } from "./ErrorInfo";
import type { LibrarySummary } from "./LibrarySummary";

export type CatalogEntry = { id: string, name: string, url: string, 
/**
 * `owner/name`.
 */
repo: string, summary: string, notes: Array<string>, publisher: CatalogPublisher, 
/**
 * Present only for a builder whose ownership has been checked.
 */
ownership: CatalogOwnership | null, 
/**
 * Present only when Habi has inspected the library and recorded it.
 */
review: CatalogReview | null, status: CatalogStatus, 
/**
 * The folders of the repository that are read, as globs.
 */
include: Array<string>, exclude: Array<string>, 
/**
 * Read at the newest release tag, not the newest commit.
 */
followsReleases: boolean, 
/**
 * What in a project makes the catalog suggest this library's skills.
 */
fitsWhen: Array<CatalogTrigger>, 
/**
 * Path segment whose folder names group the skills.
 */
groupSegment: number | null, availability: CatalogAvailability, 
/**
 * The source holding what was fetched (a preview, or the connected library).
 */
sourceId: string | null, fetched: CatalogFetched | null, 
/**
 * Counted from what was fetched.
 */
contents: LibrarySummary | null, 
/**
 * Why the last attempt to reach the repository failed, if it did.
 */
problem: ErrorInfo | null, };
