// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusState } from "./StatusState";

export type CatalogStatus = { state: StatusState, note: string | null, successor: string | null, };
