// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Recommendation } from "./Recommendation";

/**
 * The skills of one catalog library that fit a project.
 */
export type CatalogFit = { entryId: string, sourceId: string, 
/**
 * Already a connected library (not only previewed).
 */
connected: boolean, fits: Array<Recommendation>, };
