// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "./CheckStatus";

export type CheckRun = { id: string, itemKey: string, itemDigest: string, checkId: string, module: string, argv: Array<string>, cwd: string, projectFingerprint: string, startedAt: string, finishedAt: string | null, exitCode: number | null, status: CheckStatus, 
/**
 * Last part of the combined output, with secrets redacted.
 */
outputTail: string, };
