// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Latest completed result for every declared check and applicable module.
 */
export type CheckCoverage = { passed: number, failed: number, stale: number, unchecked: number, 
/**
 * Whether inspection could index all non-ignored files. A truncated
 * scan cannot establish freshness for files it never reached.
 */
inputsComplete: boolean, };
