// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingChoice } from "./BindingChoice";

export type CheckPreview = { 
/**
 * Single-use id to run exactly this command (set by the service).
 */
previewId: string, itemKey: string, itemTitle: string, itemDigest: string, checkId: string, title: string, description: string | null, module: string, 
/**
 * Program as declared.
 */
program: string, 
/**
 * Where it resolves on this machine, if found.
 */
resolvedProgram: string | null, args: Array<string>, 
/**
 * Project-relative working directory (`.` for the root).
 */
cwd: string, environment: string, timeoutSeconds: number, warnings: Array<string>, bindings: Array<BindingChoice>, 
/**
 * All bindings chosen and the program found.
 */
ready: boolean, };
