// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckArg } from "./CheckArg";
import type { CheckCwd } from "./CheckCwd";

export type CheckSpec = { id: string, title: string, description: string | null, run: Array<CheckArg>, cwd: CheckCwd, timeoutSeconds: number, };
