// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { Prerequisite } from "./Prerequisite";
import type { ReadinessState } from "./ReadinessState";

export type ClientReadiness = { client: ClientId, state: ReadinessState, prerequisites: Array<Prerequisite>, };
