// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { Precedence } from "./Precedence";

/**
 * A client that reads both a personal skill and a project's copy of it, and
 * what it does with the two.
 */
export type ClientUse = { client: ClientId, precedence: Precedence, };
