// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EcosystemFilter } from "./EcosystemFilter";

export type Condition = { "op": "all", items: Array<Condition>, } | { "op": "any", items: Array<Condition>, } | { "op": "not", item: Condition, } | { "op": "dependency", name: string, ecosystem: EcosystemFilter | null, version: string | null, } | { "op": "file", glob: string, } | { "op": "tag", tag: string, };
