// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuggestionKind } from "./SuggestionKind";

/**
 * A fact observed in a project that could become a condition. Suggestions
 * are offered one by one; none is applied unless the author adds it.
 */
export type ConditionSuggestion = { kind: SuggestionKind, value: string, label: string, module: string, 
/**
 * `file:line` the fact was read from, if any.
 */
evidence: string | null, };
