// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictKind } from "./ConflictKind";
import type { Resolution } from "./Resolution";
import type { TextDiff } from "./TextDiff";

export type Conflict = { path: string, kind: ConflictKind, item: string | null, message: string, options: Array<Resolution>, 
/**
 * What choosing `Overwrite` would change, compared to what is on disk.
 */
diff: TextDiff | null, };
