// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConflictKind = "unmanagedContent" | "localEdits" | "damagedMarkers" | "invalidConfig" | "pathCollision" | "symbolicLink";
