// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContributionOrigin = { "type": "projectSkill", projectId: string, 
/**
 * Project-relative folder containing SKILL.md.
 */
path: string, } | { "type": "libraryItem", itemId: string, } | { "type": "localSkill", skillId: string, };
