// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attention } from "./Attention";
import type { ContributionOrigin } from "./ContributionOrigin";
import type { ContributionRemote } from "./ContributionRemote";
import type { ContributionState } from "./ContributionState";
import type { Diagnostic } from "./Diagnostic";
import type { DraftFile } from "./DraftFile";
import type { ReviewStatus } from "./ReviewStatus";
import type { ShareForm } from "./ShareForm";

export type Contribution = { id: string, sourceId: string, sourceName: string, title: string, message: string, 
/**
 * Library-relative folder of the skill.
 */
itemPath: string, baseCommit: string, branch: string, state: ContributionState, origin: ContributionOrigin, form: ShareForm, files: Array<DraftFile>, validation: Array<Diagnostic>, 
/**
 * Suggestions from the project's detected facts; the author decides.
 */
suggestedTags: Array<string>, commitId: string | null, publishedUrl: string | null, 
/**
 * Why no review request was opened when the branch was pushed, if so.
 */
publishedNote: string | null, patchPath: string | null, 
/**
 * The library's current snapshot already contains exactly these files
 * (the contribution was merged, or nothing differs yet).
 */
inLibrary: boolean, 
/**
 * Where "Send for review" pushes, as the user should see it.
 */
remote: ContributionRemote | null, 
/**
 * The request on the Git host, as last read (only when the user asked).
 */
review: ReviewStatus | null, 
/**
 * 0 for the first version; each "Revise" adds one.
 */
revision: number, 
/**
 * The commit last pushed to the contribution branch.
 */
pushedCommit: string | null, 
/**
 * The private folder holding the files that would be shared, for
 * display. Edit a library-item contribution's files here; skills from
 * My skills or a project are copied again from where they live.
 */
stagingPath: string, 
/**
 * A revision is open: `cancel_revision` returns to the version before it.
 */
revising: boolean, 
/**
 * The last attempt to prepare or send failed, or someone else pushed to
 * the branch.
 */
attention: Attention | null, 
/**
 * When the branch was last pushed (and a request opened, if one was).
 */
publishedAt: string | null, createdAt: string, updatedAt: string, };
