// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewHost } from "./ReviewHost";
import type { TrackedRef } from "./TrackedRef";

/**
 * The library's remote, for the confirmation before anything is sent.
 */
export type ContributionRemote = { 
/**
 * URL or path, with any credentials removed.
 */
display: string, 
/**
 * A repository on this machine (no Git host involved).
 */
onThisMachine: boolean, 
/**
 * GitHub or GitLab when the address says so; otherwise unknown until
 * Habi asks `gh`/`glab`.
 */
host: ReviewHost | null, 
/**
 * What the library follows: the branch a request targets (the
 * repository's default branch when it follows `HEAD`).
 */
tracked: TrackedRef, 
/**
 * Why no review request can be opened from here, if so.
 */
requestUnavailable: string | null, };
