// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverageStatus } from "./CoverageStatus";

/**
 * What Habi was able to establish for one evidence area of one module.
 */
export type Coverage = { module: string, 
/**
 * `maven`, `gradle`, `npm` or `files`.
 */
area: string, status: CoverageStatus, notes: Array<string>, };
