// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredSubject } from "./DeclaredSubject";

/**
 * A user's explicit correction of detected facts. Stored per project,
 * reversible, and shown with `Declared` provenance.
 */
export type Declaration = { id: string, 
/**
 * Module id, or `*` for the whole repository.
 */
module: string, subject: DeclaredSubject, present: boolean, note: string | null, createdAt: string, };
