// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeclaredSubject = { "type": "tag", tag: string, } | { "type": "dependency", name: string, };
