// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeclaredEvidence = { date: string, result: string, environment: string | null, summary: string | null, by: string | null, };
