// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticCode } from "./DiagnosticCode";
import type { DiagnosticLevel } from "./DiagnosticLevel";

export type Diagnostic = { level: DiagnosticLevel, message: string, 
/**
 * Library-relative file the diagnostic is about.
 */
path: string | null, code?: DiagnosticCode, 
/**
 * 1-based line in `path`; for SKILL.md, in the instructions (the body
 * after the frontmatter).
 */
line?: number, };
