// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of problem a diagnostic reports, so an editor can take the
 * author to the place that fixes it. The message stays the explanation.
 */
export type DiagnosticCode = "missingDescription" | "descriptionTooLong" | "invalidName" | "duplicateName" | "emptyInstructions" | "brokenLink" | "missingReferencedFile" | "invalidMetadata" | "invalidJson" | "invalidYaml" | "possibleSecret" | "unreadableFile";
