// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticLevel } from "./DiagnosticLevel";

export type Diagnostic = { level: DiagnosticLevel, message: string, 
/**
 * Library-relative file the diagnostic is about.
 */
path: string | null, };
