// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineTag } from "./LineTag";

export type DiffLine = { tag: LineTag, oldLine: number | null, newLine: number | null, text: string, };
