// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { Diagnostic } from "./Diagnostic";

/**
 * A skill folder found in a project. It stays where it is.
 */
export type DiscoveredSkill = { 
/**
 * Project-relative folder containing SKILL.md.
 */
path: string, name: string, description: string, 
/**
 * Clients that look in this location; empty when none does.
 */
readers: Array<ClientId>, 
/**
 * Name of the library Habi installed it from, if it manages this copy.
 */
managedBy: string | null, 
/**
 * Habi applicability metadata sits next to it.
 */
hasMetadata: boolean, fileCount: number, problems: Array<Diagnostic>, digest: string, 
/**
 * Id of the local skill with the same content, if already imported.
 */
importedAs: string | null, };
