// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftFileStatus } from "./DraftFileStatus";
import type { TextDiff } from "./TextDiff";

export type DraftFile = { 
/**
 * Path in the library repository.
 */
path: string, status: DraftFileStatus, size: number, diff: TextDiff, };
