// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicateKind } from "./DuplicateKind";

export type Duplicate = { kind: DuplicateKind, skillId: string, title: string, };
