// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Ecosystem = "maven" | "gradle" | "npm" | "go" | "cargo" | "pypi" | "composer";
