// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable error returned over IPC and printed by the CLI in JSON mode.
 */
export type ErrorInfo = { code: string, message: string, };
