// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { Tri } from "./Tri";

/**
 * One node of an explanation tree.
 */
export type EvalNode = { condition: Condition, summary: string, outcome: Tri, 
/**
 * Why this outcome, in plain language.
 */
reason: string, 
/**
 * Facts that support the outcome (ids into the inspection).
 */
facts: Array<string>, 
/**
 * Declarations that decided the outcome.
 */
declarations: Array<string>, 
/**
 * Files that matched a file pattern (repository-relative).
 */
files: Array<string>, 
/**
 * Compact location of the decisive evidence, e.g. `pom.xml:31`.
 */
location: string | null, children: Array<EvalNode>, };
