// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Evidence = { 
/**
 * Repository-relative file.
 */
file: string, line: number | null, 
/**
 * A short, non-sensitive excerpt (a coordinate or key, never file bodies).
 */
excerpt: string | null, };
