// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckCoverage } from "./CheckCoverage";
import type { CheckRun } from "./CheckRun";
import type { DeclaredEvidence } from "./DeclaredEvidence";
import type { EvidenceState } from "./EvidenceState";

export type EvidenceSummary = { state: EvidenceState, declared: Array<DeclaredEvidence>, latestRun: CheckRun | null, coverage: CheckCoverage, };
