// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Excerpt = { path: string, startLine: number, lines: Array<string>, highlight: number | null, totalLines: number, };
