// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ecosystem } from "./Ecosystem";
import type { VersionInfo } from "./VersionInfo";

export type FactSubject = { "type": "dependency", ecosystem: Ecosystem, 
/**
 * `group:artifact` for JVM, the package name for npm.
 */
name: string, 
/**
 * `compile`, `test`, `dev`, `plugin`, ...
 */
scope: string | null, version: VersionInfo, } | { "type": "tag", tag: string, } | { "type": "file", path: string, role: string, };
