// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Evidence } from "./Evidence";
import type { FactOrigin } from "./FactOrigin";
import type { FactSubject } from "./FactSubject";

export type Fact = { 
/**
 * Stable within one inspection; used to link explanations to facts.
 */
id: string, module: string, subject: FactSubject, origin: FactOrigin, detector: string, evidence: Array<Evidence>, 
/**
 * Facts this one was derived from.
 */
derivedFrom: Array<string>, note: string | null, };
