// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";
import type { ChangeOp } from "./ChangeOp";
import type { ClientId } from "./ClientId";
import type { TextDiff } from "./TextDiff";

export type FileChange = { 
/**
 * Project-relative path.
 */
path: string, op: ChangeOp, kind: ChangeKind, 
/**
 * Titles of the items this change belongs to.
 */
items: Array<string>, clients: Array<ClientId>, 
/**
 * Digest expected on disk when applying (`None` = must not exist).
 */
before: string | null, 
/**
 * Digest after applying (`None` = deleted).
 */
after: string | null, explanation: string, diff: TextDiff, 
/**
 * `Some(true)` makes the written file executable, `Some(false)` clears
 * the bit, `None` keeps whatever the file has.
 */
executable: boolean | null, };
