// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A line of a package file that matched a search.
 */
export type FileMatch = { path: string, 
/**
 * 1-based.
 */
line: number, 
/**
 * The line, trimmed and shortened.
 */
text: string, };
