// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";
import type { FolderEntry } from "./FolderEntry";

export type FolderListing = { folder: FolderEntry, 
/**
 * From the home directory down to this folder.
 */
crumbs: Array<Crumb>, entries: Array<FolderEntry>, 
/**
 * More folders than are listed.
 */
truncated: boolean, };
