// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderKind } from "./FolderKind";
import type { GitFacts } from "./GitFacts";

export type FolderEntry = { name: string, 
/**
 * Full path, to browse into or open.
 */
path: string, 
/**
 * Home abbreviated.
 */
display: string, kind: FolderKind, 
/**
 * Languages and build tools, from the build files at its top.
 */
stacks: Array<string>, skills: number, 
/**
 * When it was last worked on: the last commit or checkout here, else
 * when the folder last changed.
 */
modified: string | null, 
/**
 * Read from its `.git` folder, without running Git.
 */
git: GitFacts | null, 
/**
 * Already has instructions for coding agents (`AGENTS.md`, `.claude`…).
 */
agents: boolean, 
/**
 * For a plain folder: how many of its subfolders are projects.
 */
inside: number, };
