// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a folder is, as far as opening a project goes.
 */
export type FolderKind = "project" | "skills" | "folder";
