// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A repository fetched to copy skills from, without connecting it.
 */
export type GitCopy = { sourceId: string, 
/**
 * The repository, as people say it ("acme/skills").
 */
label: string, 
/**
 * The commit that was read.
 */
snapshot: string | null, };
