// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a Git operation failed, classified from Git's own output so the UI can
 * say something more useful than "exit status 128".
 */
export type GitFailure = "network" | "authentication" | "notFound" | "gitMissing" | "rejected" | "other";
