// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitFacts = { branch: string | null, 
/**
 * Where `origin` is hosted, without credentials: `github.com/acme/app`.
 */
remote: string | null, 
/**
 * Commits made on this machine, a week per entry, oldest first.
 */
weeks: Array<number>, };
