// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where "Add skills" looks for packages.
 */
export type ImportFrom = { "type": "project", projectId: string, } | { "type": "folder", path: string, } | { "type": "library", sourceId: string, } | { "type": "gitCopy", sourceId: string, } | { "type": "machine", id: string, };
