// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { Duplicate } from "./Duplicate";

export type ImportCandidate = { 
/**
 * Where the package is inside the inspected source ("" for its root).
 */
path: string, name: string, title: string, description: string, license: string | null, hasMetadata: boolean, 
/**
 * Package-relative file paths.
 */
files: Array<string>, size: number, problems: Array<Diagnostic>, 
/**
 * False when files would be lost (links, oversized files).
 */
complete: boolean, digest: string, duplicate: Duplicate | null, 
/**
 * A free identifier to use when the name is taken.
 */
suggestedName: string | null, };
