// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportSkip } from "./ImportSkip";
import type { LocalSkillSummary } from "./LocalSkillSummary";

export type ImportOutcome = { imported: Array<LocalSkillSummary>, skipped: Array<ImportSkip>, };
