// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportCandidate } from "./ImportCandidate";

export type ImportInspection = { 
/**
 * Where the candidates were found, for display.
 */
origin: string, candidates: Array<ImportCandidate>, notes: Array<string>, };
