// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportSelection = { path: string, 
/**
 * Import under this identifier instead of the package's own.
 */
rename: string | null, };
