// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileState } from "./FileState";

export type InstalledFile = { path: string, state: FileState, 
/**
 * The library changed this file since it was installed.
 */
upstreamChanged: boolean, };
