// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectCopy } from "./ProjectCopy";

/**
 * What putting a skill on this machine would sit next to.
 */
export type InstallShadow = { name: string, title: string, 
/**
 * Projects that hold a skill of this name, and how it compares.
 */
copies: Array<ProjectCopy>, };
