// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";

/**
 * A project one of My skills is installed in.
 */
export type InstalledIn = { projectId: string, projectName: string, clients: Array<ClientId>, 
/**
 * Whether the installed copy is the skill as it is now.
 */
current: boolean, };
