// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstructionSection } from "./InstructionSection";

/**
 * A file of standing instructions (AGENTS.md, CLAUDE.md, rules).
 */
export type InstructionFile = { path: string, 
/**
 * Which convention the file follows, in plain words.
 */
convention: string, lines: number, sections: Array<InstructionSection>, 
/**
 * Problem reading the file, if any.
 */
problem: string | null, };
