// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { InstallState } from "./InstallState";
import type { InstalledFile } from "./InstalledFile";

export type Installation = { key: string, id: string, title: string, sourceName: string, snapshot: string, installedAt: string, clients: Array<ClientId>, state: InstallState, files: Array<InstalledFile>, upstreamSnapshot: string | null, };
