// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryItem } from "./LibraryItem";
import type { Source } from "./Source";

export type ItemDetail = { item: LibraryItem, source: Source, libraryName: string | null, 
/**
 * SKILL.md (or instructions) Markdown body, without frontmatter.
 */
body: string, };
