// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemFile = { 
/**
 * Relative to the item directory (or the file name for instructions).
 */
path: string, digest: string, size: number, 
/**
 * The file is executable (e.g. a script under `scripts/`).
 */
executable: boolean, };
