// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingSpec } from "./BindingSpec";
import type { CheckSpec } from "./CheckSpec";
import type { ClientId } from "./ClientId";
import type { Condition } from "./Condition";
import type { DeclaredEvidence } from "./DeclaredEvidence";
import type { Diagnostic } from "./Diagnostic";
import type { Example } from "./Example";
import type { ItemFile } from "./ItemFile";
import type { ItemKind } from "./ItemKind";
import type { McpRequirement } from "./McpRequirement";
import type { MetadataStatus } from "./MetadataStatus";
import type { Requirement } from "./Requirement";
import type { Scope } from "./Scope";
import type { Signal } from "./Signal";
import type { ToolRequirement } from "./ToolRequirement";
import type { WorkflowSpec } from "./WorkflowSpec";

export type LibraryItem = { 
/**
 * `<source id>/<item id>`: unique across sources.
 */
key: string, sourceId: string, id: string, kind: ItemKind, title: string, 
/**
 * SKILL.md `name` (the directory name clients use).
 */
name: string, description: string, 
/**
 * Library-relative directory (skills) or file (instructions).
 */
path: string, owner: string | null, 
/**
 * SKILL.md `license`, as the author wrote it.
 */
license: string | null, 
/**
 * Library-relative path of the nearest licence file in the item's folder
 * or one of its parents (a repository's root `LICENSE`, say). Habi points
 * at the terms; it does not interpret them.
 */
licenseFile: string | null, 
/**
 * The author declared the item proprietary (in `license`). Copying or
 * sharing it may not be permitted.
 */
licenseRestricted: boolean, 
/**
 * What this skill was refined from (`metadata.based-on`):
 * `<library>#<item>@<version>`. Recorded by Habi when sharing a copy.
 */
basedOn: string | null, compatibility: string | null, requirement: Requirement, priority: number, scope: Scope, appliesWhen: Condition | null, excludes: Condition | null, tools: Array<ToolRequirement>, mcp: Array<McpRequirement>, 
/**
 * `None` when not restricted.
 */
clients: Array<ClientId> | null, workflow: WorkflowSpec | null, bindings: Array<BindingSpec>, checks: Array<CheckSpec>, evidence: Array<DeclaredEvidence>, examples: Array<Example>, files: Array<ItemFile>, contentDigest: string, metadataStatus: MetadataStatus, diagnostics: Array<Diagnostic>, 
/**
 * What stands out in the item's files (commands that download and run
 * code, credential access, compiled programs, …), found by reading them
 * as data. A static reading: not a guarantee either way.
 */
signals: Array<Signal>, 
/**
 * False if some of the item's files were skipped while reading the
 * library (too large, symbolic links). Incomplete items are not installable.
 */
complete: boolean, };
