// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupCount } from "./GroupCount";
import type { LibraryLicense } from "./LibraryLicense";
import type { SignalCounts } from "./SignalCounts";

export type LibrarySummary = { 
/**
 * Skills, workflows and instructions.
 */
items: number, 
/**
 * Skills with at least one script.
 */
withScripts: number, 
/**
 * Files in `scripts/` folders, or marked executable.
 */
scriptFiles: number, withReferences: number, withAssets: number, 
/**
 * Skills that cannot be installed (invalid, or with skipped files).
 */
unusable: number, 
/**
 * Skills with at least one caution signal.
 */
cautionItems: number, 
/**
 * Skills whose most serious signal is a notice.
 */
noticeItems: number, signals: SignalCounts, 
/**
 * How the skills fall into the registry's groups (plugins, categories).
 */
groups: Array<GroupCount>, license: LibraryLicense | null, };
