// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryLicense = { 
/**
 * The licence file, library-relative.
 */
file: string, 
/**
 * Its SPDX identifier when the text is one Habi recognises exactly;
 * `None` otherwise. Habi does not guess.
 */
spdx: string | null, };
