// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { LibraryItem } from "./LibraryItem";

export type LibraryIndex = { sourceId: string, snapshot: string, name: string | null, owner: string | null, description: string | null, contact: string | null, items: Array<LibraryItem>, diagnostics: Array<Diagnostic>, };
