// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalChange } from "./LocalChange";

export type LocalChanges = { skillId: string, 
/**
 * Whether Habi has the original to compare with.
 */
known: boolean, 
/**
 * One plain sentence when it does not.
 */
detail: string | null, files: Array<LocalChange>, unchanged: number, };
