// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillOrigin } from "./SkillOrigin";

export type LocalSkillSummary = { id: string, name: string, title: string, description: string, origin: SkillOrigin, createdAt: string, updatedAt: string, 
/**
 * Set while the skill is in the trash.
 */
deletedAt: string | null, 
/**
 * Problems that block installing, exporting and sharing.
 */
errors: number, warnings: number, hasApplicability: boolean, fileCount: number, contentDigest: string, 
/**
 * For an imported copy, whether its files differ from what was copied
 * (or from the library version it last took). `None` for skills
 * written here.
 */
modifiedLocally: boolean | null, };
