// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SideChange } from "./SideChange";
import type { TextDiff } from "./TextDiff";

export type LocalChange = { path: string, change: SideChange, 
/**
 * From the original to the copy as it is now.
 */
diff: TextDiff, 
/**
 * Set when only (or also) the executable bit changed.
 */
note: string | null, };
