// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { Diagnostic } from "./Diagnostic";
import type { LocalSkillSummary } from "./LocalSkillSummary";
import type { MetadataStatus } from "./MetadataStatus";
import type { Scope } from "./Scope";
import type { ShareForm } from "./ShareForm";
import type { SkillDocument } from "./SkillDocument";
import type { SkillFileEntry } from "./SkillFileEntry";

export type LocalSkill = { summary: LocalSkillSummary, document: SkillDocument, 
/**
 * Digest of SKILL.md as loaded; saves must name it.
 */
documentDigest: string | null, 
/**
 * Set when SKILL.md cannot be read as frontmatter plus body. The file
 * is then edited as plain text until it parses again.
 */
documentError: string | null, 
/**
 * Applicability in the form the condition builder edits.
 */
form: ShareForm, 
/**
 * `habi.yaml` exactly as stored, if present.
 */
metadataText: string | null, metadataDigest: string | null, metadataStatus: MetadataStatus, appliesWhen: Condition | null, excludes: Condition | null, scope: Scope, files: Array<SkillFileEntry>, diagnostics: Array<Diagnostic>, 
/**
 * Display path of the package folder.
 */
location: string, };
