// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";

export type LockedFile = { 
/**
 * Project-relative path.
 */
path: string, digest: string, 
/**
 * Clients this copy serves.
 */
clients: Array<ClientId>, };
