// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";

export type LockedMcpEntry = { client: ClientId, file: string, server: string, 
/**
 * Digest of the entry as Habi wrote it (canonical JSON).
 */
digest: string, 
/**
 * True if the configuration file did not exist before Habi added an
 * entry to it, so Habi may delete it once it is empty again. `None` in
 * lock files written before this was recorded.
 */
created?: boolean, };
