// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { ItemKind } from "./ItemKind";
import type { LockedFile } from "./LockedFile";
import type { LockedMcpEntry } from "./LockedMcpEntry";
import type { LockedSection } from "./LockedSection";
import type { LockedSource } from "./LockedSource";

export type LockedItem = { source: LockedSource, id: string, kind: ItemKind, title: string, 
/**
 * Commit (Git) or content digest (folder) the item was installed from.
 */
snapshot: string, contentDigest: string, installedAt: string, clients: Array<ClientId>, files: Array<LockedFile>, sections: Array<LockedSection>, mcp: Array<LockedMcpEntry>, };
