// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LockedItem } from "./LockedItem";

export type LockFile = { habiLock: number, items: Array<LockedItem>, };
