// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LockedSection = { 
/**
 * Project-relative Markdown file (e.g. `AGENTS.md`).
 */
file: string, marker: string, digest: string, 
/**
 * True if the file did not exist before Habi added this section, so Habi
 * may delete it once no content is left. `None` in lock files written
 * before this was recorded.
 */
created?: boolean, };
