// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LockedSource = { 
/**
 * Normalized remote URL, or `local:<name>` for machine-local sources.
 */
identity: string, name: string, subdir: string | null, };
