// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { Diagnostic } from "./Diagnostic";
import type { ManagedInstall } from "./ManagedInstall";
import type { ProjectCopy } from "./ProjectCopy";

/**
 * A skill in one of the person's own skill folders.
 */
export type MachineSkill = { 
/**
 * Folder key and skill folder ("claude/pdf"); names it for import.
 */
id: string, folder: string, name: string, description: string, 
/**
 * Where it is, with the home folder shown as `~`.
 */
location: string, readers: Array<ClientId>, 
/**
 * The folder, or the skills folder around it, is a link.
 */
isLink: boolean, fileCount: number, digest: string, problems: Array<Diagnostic>, 
/**
 * False when files would be lost on copying (links inside, oversized files).
 */
complete: boolean, 
/**
 * Id of the skill in My skills with the same content, if one exists.
 */
importedAs: string | null, 
/**
 * Files whose text names a folder under a home directory.
 */
mentionsHome: Array<string>, inProjects: Array<ProjectCopy>, 
/**
 * Set when Habi installed it from a library.
 */
managed: ManagedInstall | null, };
