// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallState } from "./InstallState";

/**
 * A skill Habi installed into the person's own folders from a library.
 */
export type ManagedInstall = { 
/**
 * The record's key, for updating or removing it.
 */
key: string, 
/**
 * The library it came from.
 */
library: string, state: InstallState, };
