// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerSpec = { "transport": "stdio", command: string, args: Array<string>, 
/**
 * Variable name -> `${VAR}` reference. Never literal secrets.
 */
env: { [key in string]: string }, } | { "transport": "http", url: string, bearerTokenEnv: string | null, };
