// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An MCP server an installed item suggests since it was installed.
 */
export type McpSuggestion = { 
/**
 * Title of the item that suggests it.
 */
item: string, server: string, 
/**
 * Whether this plan adds it.
 */
added: boolean, };
