// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Applicability } from "./Applicability";
import type { EvalNode } from "./EvalNode";

export type ModuleMatch = { 
/**
 * Module id, or `*` for repository scope.
 */
module: string, moduleName: string, applicability: Applicability, applies: EvalNode | null, excludes: EvalNode | null, specificity: number, 
/**
 * One-line, plain-language reason.
 */
reason: string, };
