// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ecosystem } from "./Ecosystem";

export type Module = { 
/**
 * Repository-relative directory, `.` for the root.
 */
id: string, name: string, ecosystems: Array<Ecosystem>, 
/**
 * Enclosing module, if any.
 */
parent: string | null, };
