// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackedRef } from "./TrackedRef";

export type NewSource = { name: string, 
/**
 * Remote URL (https, ssh, git, scp-style) or an absolute local path.
 */
location: string, subdir: string | null, tracked: TrackedRef, };
