// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JournalState } from "./JournalState";

export type OperationSummary = { id: string, title: string, action: string, state: JournalState, createdAt: string, finishedAt: string | null, files: Array<string>, problems: Array<string>, };
