// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { ItemKind } from "./ItemKind";

export type PlanItem = { key: string, title: string, kind: ItemKind, source: string, version: string, clients: Array<ClientId>, notes: Array<string>, };
