// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conflict } from "./Conflict";
import type { FileChange } from "./FileChange";
import type { PlanAction } from "./PlanAction";
import type { PlanItem } from "./PlanItem";

export type Plan = { id: string, action: PlanAction, 
/**
 * Specific, human description of the final action.
 */
title: string, project: string, createdAt: string, items: Array<PlanItem>, changes: Array<FileChange>, 
/**
 * Must be resolved (re-plan with decisions) before applying.
 */
conflicts: Array<Conflict>, notes: Array<string>, recovery: string, };
