// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which copy a client uses when the same skill name exists for the person
 * and in a project.
 */
export type Precedence = "personalWins" | "projectWins" | "notDocumented";
