// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrerequisiteKind } from "./PrerequisiteKind";
import type { PrerequisiteStatus } from "./PrerequisiteStatus";

export type Prerequisite = { kind: PrerequisiteKind, name: string, status: PrerequisiteStatus, detail: string, purpose: string | null, hint: string | null, };
