// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShareForm } from "./ShareForm";

/**
 * The applicability rules to preview: an unsaved form, unsaved raw
 * metadata, or (with neither) what the skill has stored.
 */
export type PreviewRequest = { skillId: string | null, form: ShareForm | null, metadataText: string | null, };
