// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A small record of a project's last overview, so lists can say what fits
 * without inspecting every project again.
 */
export type ProjectSummary = { 
/**
 * Items that apply (team requirements included).
 */
fits: number, 
/**
 * Items whose applicability could not be established.
 */
needsInformation: number, 
/**
 * Libraries those items come from (source ids), most items first.
 */
sources: Array<string>, 
/**
 * Items installed in the project by Habi.
 */
installed: number, 
/**
 * Language tags (`lang:rust`), the most used first: the project's colors in lists.
 */
languages: Array<string>, at: string, };
