// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveredSkill } from "./DiscoveredSkill";
import type { InstructionFile } from "./InstructionFile";

export type ProjectKnowledge = { skills: Array<DiscoveredSkill>, instructions: Array<InstructionFile>, 
/**
 * Why the picture may be incomplete (truncated scan, unreadable folders).
 */
limits: Array<string>, inspectedAt: string, };
