// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicabilityResult } from "./ApplicabilityResult";
import type { ErrorInfo } from "./ErrorInfo";
import type { Prerequisite } from "./Prerequisite";
import type { ProjectRecord } from "./ProjectRecord";

export type ProjectPreview = { project: ProjectRecord, 
/**
 * `None` when the project could not be inspected (see `error`).
 */
result: ApplicabilityResult | null, error: ErrorInfo | null, inspectedAt: string | null, 
/**
 * Why the inspection is incomplete, if it is. Absence of evidence in an
 * incomplete inspection is "not established", never "does not apply".
 */
incomplete: Array<string>, 
/**
 * The tools the rules say the skill needs, looked up here (PATH and the
 * project; nothing is run). They never change whether it applies.
 */
prerequisites: Array<Prerequisite>, };
