// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientUse } from "./ClientUse";

/**
 * The same folder name, found in a project.
 */
export type ProjectCopy = { projectId: string, projectName: string, 
/**
 * Project-relative folder holding the copy.
 */
path: string, 
/**
 * The same files, byte for byte.
 */
identical: boolean, 
/**
 * Clients that read both this copy and the personal one; empty when no
 * client sees both, so neither hides the other.
 */
sharedReaders: Array<ClientUse>, };
