// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";
import type { FolderEntry } from "./FolderEntry";

export type ProjectPlaces = { home: Crumb, 
/**
 * The usual code folders that exist here (`~/Workspace`, `~/code`…).
 */
roots: Array<Crumb>, 
/**
 * Repositories in those folders, most recently changed first.
 */
found: Array<FolderEntry>, };
