// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coverage } from "./Coverage";
import type { Fact } from "./Fact";
import type { Module } from "./Module";
import type { RepositoryInfo } from "./RepositoryInfo";
import type { ScanReport } from "./ScanReport";

export type ProjectInspection = { root: string, name: string, repository: RepositoryInfo, modules: Array<Module>, facts: Array<Fact>, coverage: Array<Coverage>, scan: ScanReport, 
/**
 * Changes when any manifest or recognized file changes.
 */
fingerprint: string, inspectedAt: string, };
