// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Declaration } from "./Declaration";
import type { Installation } from "./Installation";
import type { ProjectInspection } from "./ProjectInspection";
import type { ProjectRecord } from "./ProjectRecord";
import type { Recommendation } from "./Recommendation";
import type { Source } from "./Source";

export type ProjectOverview = { project: ProjectRecord, inspection: ProjectInspection, declarations: Array<Declaration>, recommendations: Array<Recommendation>, sources: Array<Source>, 
/**
 * Installed items whose source or item is not available on this machine.
 */
orphaned: Array<Installation>, };
