// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodePlace } from "./CodePlace";
import type { Crumb } from "./Crumb";
import type { FolderEntry } from "./FolderEntry";

export type ProjectPlaces = { home: Crumb, 
/**
 * Folders in the home folder that hold projects, the fullest first.
 */
roots: Array<CodePlace>, 
/**
 * The projects in them (and any right in the home folder), latest work first.
 */
found: Array<FolderEntry>, 
/**
 * How many there are, though only the latest are in `found`.
 */
total: number, };
