// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSummary } from "./ProjectSummary";

export type ProjectRecord = { id: string, name: string, 
/**
 * Display path (home abbreviated).
 */
path: string, exists: boolean, lastOpenedAt: string, exclusions: Array<string>, 
/**
 * Part of the explicitly labeled sample workspace.
 */
sample: boolean, 
/**
 * What fit when the project was last looked at; `None` until then.
 */
summary: ProjectSummary | null, };
