// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRecord } from "./ProjectRecord";

/**
 * What came of choosing a folder to open as a project.
 */
export type ProjectPick = { "kind": "opened", project: ProjectRecord, } | { "kind": "skills", 
/**
 * Full path, as chosen.
 */
path: string, name: string, skills: number, };
