// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PruneReport = { 
/**
 * Records of finished operations removed (beyond the newest per project).
 */
operationsRemoved: number, 
/**
 * Library previews, never connected, discarded for being old.
 */
previewsRemoved: number, 
/**
 * Earlier library snapshots removed.
 */
snapshotsRemoved: number, 
/**
 * Stored file contents removed because nothing kept refers to them.
 */
objectsRemoved: number, bytesFreed: number, 
/**
 * Projects and libraries skipped because another operation was using them.
 */
skippedBusy: number, };
