// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublishOutcome = { remote: string, branch: string, pullRequestUrl: string | null, 
/**
 * Why no pull request was opened, if none was.
 */
pullRequestNote: string | null, 
/**
 * The branch already had an open request; it now shows this revision.
 */
updatedExisting: boolean, };
