// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Prerequisite } from "./Prerequisite";
import type { ReadinessState } from "./ReadinessState";

export type Readiness = { state: ReadinessState, prerequisites: Array<Prerequisite>, };
