// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { ClientReadiness } from "./ClientReadiness";
import type { Prerequisite } from "./Prerequisite";
import type { ReadinessState } from "./ReadinessState";

export type Readiness = { state: ReadinessState, prerequisites: Array<Prerequisite>, 
/**
 * Readiness for each supported agent; configuration in one agent does
 * not establish readiness in another.
 */
byClient: Array<ClientReadiness>, 
/**
 * Installed agents, or the supported agents detected in this project.
 */
assessedClients: Array<ClientId>, };
