// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicabilityResult } from "./ApplicabilityResult";
import type { Basis } from "./Basis";
import type { EvidenceSummary } from "./EvidenceSummary";
import type { Group } from "./Group";
import type { InstallState } from "./InstallState";
import type { Installation } from "./Installation";
import type { ItemSummary } from "./ItemSummary";
import type { NextAction } from "./NextAction";
import type { Readiness } from "./Readiness";

export type Recommendation = { item: ItemSummary, group: Group, applicability: ApplicabilityResult, 
/**
 * Who set the rule `applicability` evaluated.
 */
basis: Basis, readiness: Readiness, installState: InstallState, installation: Installation | null, evidence: EvidenceSummary, nextAction: NextAction, 
/**
 * Copies of this skill in the project that Habi does not manage.
 */
unmanagedCopies: Array<string>, };
