// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";

export type RefreshOutcome = { source: Source, changed: boolean, previous: string | null, current: string, added: Array<string>, removed: Array<string>, updated: Array<string>, };
