// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * For reviewers: where a contribution's rules apply among the author's own
 * projects (sample projects are not counted). Plain text, inserted into the
 * message only when the author chooses; it names projects, never paths.
 */
export type Rehearsal = { 
/**
 * Empty when there was nothing to check against.
 */
text: string, 
/**
 * Projects the rules were evaluated against.
 */
projects: number, samplesSkipped: number, };
