// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A skill named in an update report.
 */
export type ReportedSkill = { id: string, title: string, };
