// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryKind } from "./RepositoryKind";

export type RepositoryInfo = { kind: RepositoryKind, 
/**
 * Current branch, read from Git metadata files without running Git.
 */
branch: string | null, 
/**
 * Display form of the enclosing repository root when it differs from the
 * selected directory.
 */
repositoryRoot: string | null, isMonorepo: boolean, 
/**
 * Workspace tooling that declares multiple packages (npm workspaces,
 * pnpm, Maven modules, Gradle includes, ...).
 */
workspaceSignals: Array<string>, };
