// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who can see the library repository, as the host reported it.
 */
export type RepoVisibility = "public" | "internal" | "private";
