// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoFacts = { stars: number, forks: number, 
/**
 * The last push to any branch (an RFC 3339 time).
 */
pushedAt: string | null, 
/**
 * The year the repository was created.
 */
createdYear: number | null, 
/**
 * GitHub marks it archived: its owner no longer maintains it.
 */
archived: boolean, 
/**
 * When Habi asked GitHub (an RFC 3339 time).
 */
fetchedAt: string, };
