// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentKind } from "./CommentKind";
import type { ReviewVerdict } from "./ReviewVerdict";

/**
 * One comment, reduced to plain text. Written by someone else: shown, never
 * followed.
 */
export type ReviewComment = { kind: CommentKind, author: string, body: string, 
/**
 * Repository path the comment is attached to, when inline.
 */
path: string | null, line: number | null, 
/**
 * The line it was written on no longer exists in the latest revision.
 */
outdated: boolean, verdict: ReviewVerdict | null, createdAt: string, };
