// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoVisibility } from "./RepoVisibility";
import type { ReviewComment } from "./ReviewComment";
import type { ReviewHost } from "./ReviewHost";
import type { ReviewState } from "./ReviewState";

/**
 * What the host reported, and when Habi asked.
 */
export type ReviewStatus = { host: ReviewHost, 
/**
 * Only kept when it points at the library's own host.
 */
url: string | null, number: number, state: ReviewState, 
/**
 * The commit the host sees at the head of the branch.
 */
headCommit: string | null, 
/**
 * People whose latest review approves the change.
 */
approvedBy: Array<string>, comments: Array<ReviewComment>, 
/**
 * More comments exist than Habi shows.
 */
commentsTruncated: boolean, 
/**
 * The branch the request targets, as the host reported it.
 */
targetBranch: string | null, 
/**
 * The repository's visibility, when the host's answer includes it
 * (GitHub does; GitLab's merge request does not).
 */
visibility: RepoVisibility | null, checkedAt: string, };
