// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRecord } from "./ProjectRecord";
import type { Source } from "./Source";

export type SampleWorkspace = { sources: Array<Source>, projects: Array<ProjectRecord>, };
