// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanReport = { filesSeen: number, directoriesSkipped: Array<string>, 
/**
 * True if a traversal limit stopped the scan early. File-pattern absence
 * is then unknown rather than false.
 */
truncated: boolean, limitsHit: Array<string>, unreadable: Array<string>, symlinksSkipped: number, largeFilesSkipped: number, elapsedMs: number, };
