// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { 
/**
 * 0 disables scheduled refresh.
 */
autoRefreshHours: number, 
/**
 * Whether Habi asks GitHub for a newer release while it is open. Installing
 * one always waits for the person.
 */
checkForUpdates: boolean, 
/**
 * Whether the welcome overlay opens when Habi starts. The person turns it
 * off from the overlay itself; Settings turns it back on.
 */
showWelcome: boolean, };
