// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExampleEntry } from "./ExampleEntry";
import type { MatchMode } from "./MatchMode";
import type { ToolEntry } from "./ToolEntry";

/**
 * The author-facing form. Turned into `habi.yaml`.
 */
export type ShareForm = { title: string, owner: string, repositoryScope: boolean, 
/**
 * False when the existing conditions are richer than this form can
 * express; they are then kept unchanged.
 */
conditionsEditable: boolean, matchMode: MatchMode, appliesTags: Array<string>, appliesDependencies: Array<string>, appliesFiles: Array<string>, excludeTags: Array<string>, excludeDependencies: Array<string>, tools: Array<ToolEntry>, examples: Array<ExampleEntry>, };
