// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change on one side, relative to the version you copied.
 */
export type SideChange = "added" | "modified" | "removed";
