// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts of signals by severity.
 */
export type SignalCounts = { caution: number, notice: number, info: number, };
