// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignalKind = "downloadAndRun" | "destructive" | "credentialFile" | "environmentSecret" | "privileged" | "dynamicExecution" | "network" | "packageInstall" | "nativeBinary" | "opaqueFile" | "executableData" | "hiddenText" | "notFullyRead";
