// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalKind } from "./SignalKind";
import type { SignalSeverity } from "./SignalSeverity";

export type Signal = { kind: SignalKind, severity: SignalSeverity, summary: string, 
/**
 * Library-relative file.
 */
path: string, 
/**
 * First line (1-based) where it was seen, when it is about a line.
 */
line: number | null, 
/**
 * The line itself (shortened), or what was seen.
 */
detail: string | null, 
/**
 * How many more places in the same file show the same thing.
 */
more: number, };
