// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional starting structures for the instructions. Each is a shape that
 * works for an agent as written; the author fills in what is specific to
 * their code.
 */
export type SkillTemplate = "blank" | "workflow" | "troubleshooting" | "reviewProcedure" | "toolAssisted" | "implementationGuide";
