// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Upstream } from "./Upstream";

/**
 * Where a local skill came from. Attribution only; never used for matching.
 */
export type SkillOrigin = { "type": "created" } | { "type": "createdForProject", projectName: string, } | { "type": "folder", path: string, } | { "type": "project", projectName: string, path: string, } | { "type": "library", sourceName: string, sourceIdentity: string, itemId: string, snapshot: string, 
/**
 * Where the original lives and who stands behind it, as it was when
 * the copy was made. Absent on copies made before Habi recorded it.
 */
upstream: Upstream | null, } | { "type": "instructions", projectName: string, path: string, startLine: number, endLine: number, };
