// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { ProjectPreview } from "./ProjectPreview";
import type { Scope } from "./Scope";

/**
 * How the rules being edited evaluate against registered projects. This
 * previews the rules only — not the skill's quality or an agent's behavior.
 */
export type SkillPreview = { appliesWhen: Condition | null, excludes: Condition | null, scope: Scope, 
/**
 * Why the rules could not be evaluated (invalid metadata).
 */
problem: string | null, projects: Array<ProjectPreview>, };
