// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The parts of SKILL.md the editor works on.
 */
export type SkillDocument = { 
/**
 * The skill identifier (`name` in the Agent Skills format).
 */
name: string, description: string, 
/**
 * Markdown instructions, without frontmatter.
 */
body: string, };
