// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledIn } from "./InstalledIn";
import type { UpstreamState } from "./UpstreamState";

/**
 * Where one of My skills stands outside its own files.
 */
export type SkillStanding = { skillId: string, installedIn: Array<InstalledIn>, 
/**
 * For a library copy: how the library's version compares.
 */
upstream: UpstreamState | null, };
