// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillFileContent = { path: string, text: string | null, size: number, binary: boolean, digest: string, };
