// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillFileContent = { path: string, text: string | null, size: number, binary: boolean, digest: string, 
/**
 * A `data:` URL for images Habi can show (PNG, JPEG, GIF, WebP, SVG
 * under 2 MB). Shown in an `<img>`, where SVG scripts never run.
 */
preview: string | null, };
