// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who stands behind a library. Habi does not guess this from a URL: the
 * user says so when connecting it, and can change it later.
 */
export type SourceRole = "team" | "community";
