// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One version of a library: a release tag, or a branch at a commit.
 */
export type SourceVersion = { 
/**
 * The release tag (`v6.4.2`) or the branch name (`main`).
 */
label: string, 
/**
 * Whether `label` is a release tag.
 */
release: boolean, commit: string, };
