// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInfo } from "./ErrorInfo";
import type { Freshness } from "./Freshness";
import type { SourceKind } from "./SourceKind";
import type { TrackedRef } from "./TrackedRef";

export type Source = { id: string, name: string, kind: SourceKind, 
/**
 * URL, or a local path shown with `~`.
 */
location: string, subdir: string | null, tracked: TrackedRef, createdAt: string, 
/**
 * Commit (Git) or content digest (directory) of the cached snapshot.
 */
snapshot: string | null, snapshotAt: string | null, commitSummary: string | null, lastAttemptAt: string | null, lastError: ErrorInfo | null, 
/**
 * Integrity warnings such as a moved tag or rewritten history.
 */
warning: string | null, freshness: Freshness, };
