// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceVersion } from "./SourceVersion";

/**
 * What a check for updates found. Nothing was downloaded, and nothing
 * changed: applying it is the user's decision (`Sources::refresh`).
 */
export type SourceUpdate = { sourceId: string, 
/**
 * What is read now.
 */
current: SourceVersion | null, 
/**
 * What the remote has now.
 */
latest: SourceVersion, 
/**
 * The remote has something other than what is read now.
 */
available: boolean, checkedAt: string, };
