// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One library's part in a project.
 */
export type SourceTally = { sourceId: string, 
/**
 * Its items that apply to the project (team requirements included).
 */
fits: number, 
/**
 * Titles of its items installed in the project, whatever their fit.
 */
installed: Array<string>, };
