// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInfo } from "./ErrorInfo";
import type { Freshness } from "./Freshness";
import type { SourceKind } from "./SourceKind";
import type { SourceRole } from "./SourceRole";
import type { TrackedRef } from "./TrackedRef";

export type Source = { id: string, name: string, kind: SourceKind, role: SourceRole, 
/**
 * URL, or a local path shown with `~`.
 */
location: string, subdir: string | null, tracked: TrackedRef, createdAt: string, 
/**
 * Commit (Git) or content digest (directory) of the cached snapshot.
 */
snapshot: string | null, snapshotAt: string | null, commitSummary: string | null, lastAttemptAt: string | null, lastError: ErrorInfo | null, 
/**
 * Integrity warnings such as a moved tag or rewritten history.
 */
warning: string | null, freshness: Freshness, 
/**
 * Part of the explicitly labeled sample workspace. Sample libraries are
 * matched only against sample projects.
 */
sample: boolean, 
/**
 * Items (skills, workflows, instructions) in the cached snapshot; 0
 * before the first fetch.
 */
skillCount: number, 
/**
 * Fetched so it can be inspected, but not connected: previews are kept
 * out of every list, recommendation and installation until connected.
 */
preview: boolean, 
/**
 * The catalog entry this source was added from, if any.
 */
catalogId: string | null, 
/**
 * Only files matching one of these globs are read (all files when empty).
 */
include: Array<string>, 
/**
 * Files matching one of these globs are never read.
 */
exclude: Array<string>, 
/**
 * The branch the remote's `HEAD` named at the last check.
 */
defaultBranch: string | null, };
