// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillTemplate } from "./SkillTemplate";

/**
 * A starter as the editor offers it.
 */
export type TemplateInfo = { template: SkillTemplate, label: string, 
/**
 * One line on when this shape fits.
 */
summary: string, body: string, };
