// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hunk } from "./Hunk";

export type TextDiff = { hunks: Array<Hunk>, added: number, removed: number, 
/**
 * Content is not text; only sizes/digests are shown.
 */
binary: boolean, 
/**
 * The diff was cut to keep the preview readable.
 */
truncated: boolean, };
