// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolRequirement = { name: string, commands: Array<string>, purpose: string | null, installHint: string | null, };
