// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of the update has arrived, sent as the `update-progress` event.
 */
export type UpdateProgress = { downloaded: number, 
/**
 * `None` when the server did not say how large the download is.
 */
total: number | null, };
