// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportedSkill } from "./ReportedSkill";
import type { SourceVersion } from "./SourceVersion";

/**
 * What an update changed in a library, kept until it is dismissed so the
 * changes can be read, and marked in the library, after the fact.
 */
export type UpdateReport = { sourceId: string, from: SourceVersion | null, to: SourceVersion, at: string, added: Array<ReportedSkill>, updated: Array<ReportedSkill>, removed: Array<ReportedSkill>, };
