// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A newer release, as the UI shows it.
 */
export type UpdateInfo = { version: string, currentVersion: string, 
/**
 * When it was published (RFC 3339), if the release says.
 */
date: string | null, 
/**
 * What changed, as Markdown: the release's section of the changelog.
 */
notes: string | null, };
