// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The original of an adopted skill, kept with the copy so it can always be
 * traced back, credited, and (if its owner allows) shared back.
 */
export type Upstream = { 
/**
 * The repository it came from (a web address), when it has one.
 */
url: string | null, 
/**
 * The skill's folder in that repository.
 */
path: string, 
/**
 * The licence the skill declares, else the repository's when known.
 */
license: string | null, 
/**
 * Who publishes the repository, as the catalog names them.
 */
publisher: string | null, 
/**
 * The catalog entry it came from, if any.
 */
catalogId: string | null, };
