// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpstreamFile } from "./UpstreamFile";
import type { UpstreamStatus } from "./UpstreamStatus";

export type UpstreamPlan = { status: UpstreamStatus, 
/**
 * Files that differ on at least one side (unchanged files are counted).
 */
files: Array<UpstreamFile>, unchanged: number, take: number, keep: number, conflicts: number, 
/**
 * Names exactly what was reviewed; applying refuses if the skill or
 * the library changed since.
 */
token: string, 
/**
 * Why the update cannot be applied as it stands, if it cannot.
 */
blocked: string | null, };
