// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SideChange } from "./SideChange";
import type { TextDiff } from "./TextDiff";
import type { UpstreamFileStatus } from "./UpstreamFileStatus";

export type UpstreamFile = { path: string, status: UpstreamFileStatus, libraryChange: SideChange | null, yourChange: SideChange | null, 
/**
 * From the version you copied to the library's version.
 */
libraryDiff: TextDiff | null, 
/**
 * From the version you copied to yours.
 */
yourDiff: TextDiff | null, 
/**
 * Set when the executable bit differs (contents may be identical).
 */
note: string | null, };
