// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a library copy relates to its library now.
 */
export type UpstreamState = "unchanged" | "changed" | "removed" | "unavailable";
