// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A per-file choice for a conflict.
 */
export type UpstreamChoice = "keepMine" | "takeLibrary";
