// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpstreamState } from "./UpstreamState";

export type UpstreamStatus = { skillId: string, state: UpstreamState, 
/**
 * The library's name as recorded when the skill was copied.
 */
sourceName: string, 
/**
 * The connected source it was matched to, if any.
 */
sourceId: string | null, itemId: string, 
/**
 * Snapshot the copy was made from (or last updated to).
 */
originSnapshot: string, 
/**
 * The library's current snapshot, when known.
 */
currentSnapshot: string | null, 
/**
 * One plain sentence for `removed` and `unavailable`.
 */
detail: string | null, };
