// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionState } from "./VersionState";

export type VersionInfo = { state: VersionState, 
/**
 * What the manifest says, e.g. `${liquibase.version}` or `^18.2.0`.
 */
declared: string | null, 
/**
 * The concrete version, when established.
 */
resolved: string | null, 
/**
 * Why the version is not resolved, or where it was resolved from.
 */
note: string | null, };
