// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowStep = { title: string, detail: string | null, references: Array<string>, expected: string | null, };
