// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowStep } from "./WorkflowStep";

export type WorkflowSpec = { steps: Array<WorkflowStep>, artifacts: Array<string>, };
