#!/usr/bin/env node
/**
 * Real data for the site: what Habi recommends for the example repositories.
 *
 * Runs the `habi` CLI against the fixture repositories and libraries in a
 * throwaway HABI_HOME, and writes a slim projection to
 * src/data/recommendations.json. Nothing on the page is invented: titles,
 * groups, reasons and file:line evidence come from the core.
 *
 *   cargo build -p habi-cli && pnpm snapshot
 *   HABI_BIN=/path/to/habi pnpm snapshot
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const bin = process.env.HABI_BIN ?? join(root, "target/debug/habi");
const home = mkdtempSync(join(tmpdir(), "habi-site-"));
const env = { ...process.env, HABI_HOME: home };

const REPOS = ["billing-service", "platform-monorepo", "storefront-web", "orders-api"];
const LIBRARIES = [
  ["Platform team", "fixtures/libraries/example-team-library"],
  ["Security guild", "fixtures/libraries/security-guild-library"],
];

// The same plain names the app uses for technology tags.
const tagsSource = readFileSync(join(root, "apps/desktop/src/lib/tags.ts"), "utf8");
const TAGS = new Map([...tagsSource.matchAll(/"([a-z-]+:[a-z0-9-]+)": "([^"]+)"/g)].map((m) => [m[1], m[2]]));

const habi = (...args) => execFileSync(bin, args, { env, cwd: root, encoding: "utf8" });

/** Every leaf that holds, with where it was seen. */
function evidence(node, out = []) {
  if (!node) return out;
  if (node.children?.length) for (const c of node.children) evidence(c, out);
  else if (node.outcome === "true" && node.location) out.push(node.location);
  return out;
}

try {
  for (const [name, path] of LIBRARIES) habi("source", "add", name, path);
  habi("source", "refresh");

  const repos = REPOS.map((repo) => {
    const dir = join("fixtures/repos", repo);
    const facts = JSON.parse(habi("inspect", "--json", "-C", dir));
    const tags = new Set(facts.facts.map((f) => f.subject.tag).filter(Boolean));
    const stack = [...TAGS.keys()].filter((t) => tags.has(t)).map((t) => TAGS.get(t));
    const recs = JSON.parse(habi("recommend", "--json", "-C", dir));
    const items = recs
      .filter((r) => r.group !== "available")
      .map((r) => {
        const a = r.applicability;
        const where = [...new Set(a.modules.flatMap((m) => evidence(m.applies)))];
        return {
          title: r.item.title,
          library: r.item.sourceName,
          kind: r.item.kind,
          group: r.group,
          state: a.applicability,
          reason: a.reason,
          evidence: where.slice(0, 3),
        };
      });
    return { name: repo, stack, modules: facts.modules.length, items };
  });

  const out = {
    note: "Generated by website/scripts/snapshot.mjs from the habi CLI and the repository's fixtures.",
    libraries: LIBRARIES.map(([name]) => name),
    repos,
  };
  writeFileSync(join(here, "../src/data/recommendations.json"), `${JSON.stringify(out, null, 2)}\n`);
  console.log(`Wrote ${repos.length} repositories: ${repos.map((r) => `${r.name} (${r.items.length})`).join(", ")}`);
} finally {
  rmSync(home, { recursive: true, force: true });
}
